### ISSUE TITLE
Latest docker image outdated?

### ISSUE THREAD

**Issue by meyskens** [multiarch/qemu-user-static#1]
On a fresh C2M with `docker run --rm --privileged multiarch/qemu-user-static:register` done I get this error `/build/qemu-Ee59aw/qemu-2.0.0+dfsg/tcg/optimize.c:362: tcg fatal error` (qemu bug for sure) but it seems the version is 2.0.0 and not 2.5.0

**Comment by moul** [comment]
`docker run --rm --privileged multiarch/qemu-user-static:register` won't use qemu, it will only register (configure) the binfmt,

did you ran another image after this to get this error ?

**Comment by meyskens** [comment]
oops my fault. I got it fixed with an older build of npm.

**Comment by moul** [comment]
ok :)
