### ISSUE TITLE
Can we do a release of v2.7.0?

### ISSUE THREAD

**Issue by luxas** [multiarch/qemu-user-static#11]
Hi, is it possible to soon do a new release for v2.7?
That would be cool

**Comment by moul** [comment]
Yep sure, @QuentinPerez do you have some time to do it? I won't have for the 3 following days

**Comment by moul** [comment]
Done

**Comment by luxas** [comment]
Many thanks from me and the Kubernetes side @moul and @QuentinPerez!
ref: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/multi-platform.md
