### ISSUE TITLE
Network  connect time out

### ISSUE THREAD

**Issue by xspython** [multiarch/qemu-user-static#113]
I used qemu-aarch64-static to run a docker in x86 environment, - net bridge
ping 172.17.0.1 time out ?

  docker run -d --name a2 --hostname a2   -v /usr/bin/qemu-aarch64-static:/usr/bin/qemu-aarch64-static ln1:v1  /sbin/init                           a79c45ddbf0f82e75b7c1651dd17e9a022c652040b6028ce56c4600242bbc55c
[root@ln4 ~]# docker exec -it a2 /bin/bash
root@a2:/# ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
38: eth0@if39: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:11:00:02 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.2/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever
root@a2:/#  ping 172.17.0.1
PING 172.17.0.1 (172.17.0.1) 56(84) bytes of data.

**Comment by xspython** [comment]
Network not supported?

**Comment by umarcor** [comment]
@xspython, I cannot reproduce the network issue... The following works for me:

```sh
# docker run --rm -it arm64v8/ubuntu:18.04 bash
root@119facca28e0:/# ping google.com
bash: ping: command not found

root@119facca28e0:/# apt update -qq
All packages are up to date.

root@119facca28e0:/# apt-get install -y iputils-ping iproute2
Reading package lists... Done
...

root@119facca28e0:/# ping google.com
PING google.com (172.217.16.238) 56(84) bytes of data.
64 bytes from 172.217.16.238 (172.217.16.238): icmp_seq=1 ttl=37 time=32.1 ms
64 bytes from 172.217.16.238 (172.217.16.238): icmp_seq=2 ttl=37 time=33.4 ms
64 bytes from 172.217.16.238 (172.217.16.238): icmp_seq=3 ttl=37 time=32.9 ms
^C
--- google.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 32.195/32.880/33.474/0.566 ms
root@119facca28e0:/# ping 172.17.0.1
PING 172.17.0.1 (172.17.0.1) 56(84) bytes of data.
64 bytes from 172.17.0.1: icmp_seq=1 ttl=64 time=0.085 ms
64 bytes from 172.17.0.1: icmp_seq=2 ttl=64 time=0.034 ms
64 bytes from 172.17.0.1: icmp_seq=3 ttl=64 time=0.099 ms
^C
--- 172.17.0.1 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2051ms
rtt min/avg/max/mdev = 0.034/0.072/0.099/0.029 ms
```

Hence, network seems to be supported. Nonetheless, you seem to not be using any of the resources provided in this repo or in dbhi/qus. How are you getting `qemu-aarch64-static`? Which version is it? What image is `ln1` based on?

Anyway, I see some error messages when running `ip`:

```sh
root@119facca28e0:/# ip addr show
Unsupported setsockopt level=270 optname=11
Unknown QEMU_IFLA_INFO_KIND ipip
Unknown QEMU_IFLA_INFO_KIND ip6tnl
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
...
```

It might be worth reporting this upstream: https://bugs.launchpad.net/qemu

**Comment by xspython** [comment]
Hello, I found the problem. It's RedHat 7.2 and docker 19.03 bridge.ko Module incompatibility

**Comment by xspython** [comment]
Hello, I found the problem. It's RedHat 7.2 and docker 19.03 bridge.ko Module incompatibility
