### ISSUE TITLE
'ifconfig' does not work when run arm64 docker from x64 host

### ISSUE THREAD

**Issue by xgwang** [multiarch/qemu-user-static#115]
**Is this a bug report, feature (enhancement) request or question? (leave only one on its own line)**

/kind question

**Description:**

i am running an arm64 docker on x64 host, it is straightforward with qemu-user-static, but inside the arm64 docker, `ifconfig` does not seem good while other binaries are fine. 

**Steps to reproduce the issue:**

1.
```bash
docker run --rm -it -v /usr/bin/qemu-aarch64-static:/usr/bin/qemu-aarch64-static arm64v8/ubuntu:18.04 bash
apt update && apt install -y net-tools iputils-ping iproute2
ping 8.8.8.8
# result is fine
ifconfig
```

**Describe the results you received:**
```bash
: error fetching interface information: Device not found
```

**Describe the results you expected:**
```bash
# show device details
```

**Environment:**

* QEMU version: (if you can know it):
qemu-aarch64-static: qemu-aarch64 version 5.0.0 (qemu-5.0.0-2.fc33)
* Container application: Docker

**Output of `docker version`, `podman version` or `singularity version`**

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Additional information optionally:**

**Comment by SuperSandro2000** [comment]
Can you use ``ip``? This works for me.

**Comment by xgwang** [comment]
> Can you use `ip`? This works for me.

yes, for this single command, `ip` works.

i am trying to communicate an arm64 software stack in docker using multicast, but does not come to any solution.

when i try to debug with tcpdump, it says:
```bash
tcpdump: Can't get Bluetooth device list via ioctl: Function not implemented
```
i am not sure if network layer is fully supported.

**Comment by SuperSandro2000** [comment]
Maybe this helps you https://github.com/moby/moby/issues/16208#issuecomment-268378445

**Comment by xgwang** [comment]
> Maybe this helps you [moby/moby#16208 (comment)](https://github.com/moby/moby/issues/16208#issuecomment-268378445)

finally i am not able to figure it out in my case: multicast + docker + qemu user static + arm64 binary stack 

also i cannot apply a full simulation in my target environment. 

i pick up a workaround to use x64 peer for my arm64 binary stack.
