### ISSUE TITLE
mount: permission denied (are you root?)

### ISSUE THREAD

**Issue by Liveshkumar** [multiarch/qemu-user-static#133]
while trying to run cmd   docker run -it --name qemu multiarch/qemu-user-static 
getting  an error 
mount: permission denied (are you root?)
mount: permission denied (are you root?)
used su cmd to become root user and then used sudo too but still getting the same error

**Comment by Dzeri96** [comment]
I have the same problem when running rootless docker. Any idea how to fix it?
