### ISSUE TITLE
The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

### ISSUE THREAD

**Issue by dawoodahmed-jazz** [multiarch/qemu-user-static#134]
I am trying to run the following command on Macbook M1 pro

`ocker run --rm --privileged multiarch/qemu-user-static --reset -p yes `

but getting the following error on this

**The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested**

**Comment by antode** [comment]
Same here, but on arm qemu virtual machine, I think it because of https://github.com/multiarch/qemu-user-static#supported-host-architectures
```
Supported host architectures
x86_64
Currently qemu-user-static is not available on other host architectures such as aarch64. Run uname -m to check it on your environment.
```
but I have no idea how to revert changes made by container

**Comment by junaruga** [comment]
Try https://github.com/dbhi/qus supporting arm64 maybe written in [this doc](https://github.com/multiarch/qemu-user-static/blob/master/docs/examples.md#sister-projects).

> but I have no idea how to revert changes made by container

https://github.com/multiarch/qemu-user-static/blob/d9c81fc6ca9f6e4b53b9b2ffc7cd72c8cc997073/containers/latest/register.sh#L20

To clean your environment, if you have the installed binfmt_misc files,

```
$ ls /proc/sys/fs/binfmt_misc/qemu-*
```

Run the following command with the root `#` user, not `$ sudo ...` by your own responsibility. Be careful!

```
# find /proc/sys/fs/binfmt_misc -type f -name 'qemu-*' -exec sh -c 'echo -1 > {}' \;
```

Then if you see the `multiarch/qemu-user-static` images, just remove it.

```
$ docker images
```

e.g. Remove all the container images.

```
$ docker system prune -a -f
```

**Comment by junaruga** [comment]
I would close this ticket, as my last comment answered for this issue. If you want this repo to support arm64, the pull-request is always welcome. I suppose some maintainers might review it.
