### ISSUE TITLE
Can we get a healthcheck?

### ISSUE THREAD

**Issue by kevin-lindsay-1** [multiarch/qemu-user-static#136]
**Is this a bug report, feature (enhancement) request or question? (leave only one on its own line)**

/kind enhancement

**Description:**

I use GitLab CI runners on Kubernetes, and attach this as a `service` in the `.gitlab-ci.yml`.

This container doesn't appear to have a healthcheck, so kubernetes shows the pod as `NotReady` even when it's working just fine.

I don't really think we need much of a "real" healthcheck, but having one would at least make it clear to other systems that things are working fine, rather than ambiguous.

**Describe the results you received:**

Get `NotReady` on pod where this container is attached.

**Describe the results you expected:**

Get `Running` on pod where this container is attached.

**Comment by lafin** [comment]
Thanks for your feedback.
https://docs.gitlab.com/runner/executors/docker.html#the-services-health-check
As for this, I think it is not enough to add a dummy health check.

**Comment by kevin-lindsay-1** [comment]
@lafin I have no preference for how the health check is implemented; every container typically has its own flavor.

I'm simply proposing to have a health check at all, because right now the container never enters a "healthy" state, which in kubernetes can introduce unintended behaviors if a pod never becomes healthy.

I proposed a dummy health check only because a health check didn't look like it was considered very important previously, as this container doesn't currently have a health check at all.
