### ISSUE TITLE
no binary is provided in the latest release

### ISSUE THREAD

**Issue by horis233** [multiarch/qemu-user-static#141]
**Is this a bug report, feature (enhancement) request or question? (leave only one on its own line)**

/kind question

**Description:**

Is there any reason why we stop providing binary in the latest release?
There are many users who use a command like this to get binary to build docker images `RUN wget -O /qemu-ppc64le-static https://github.com/multiarch/qemu-user-static/releases/latest/download/qemu-ppc64le-static`.

Since no binary is provided in the latest release, they need to change to use a release version to get the binary instead of the latest tag.

**Describe the results you received:**

Failed to get binary from the latest release.

**Describe the results you expected:**

Users can still use the latest tag to download binary and receive fixes and updates.

**Comment by pgodowski** [comment]
One clarifying question to the community - will the binaries for the newest AND older releases being published? (i.e. older binaries will not be removed?)

**Comment by lafin** [comment]
@horis233 @pgodowski Thanks for your feedback. Binaries are available for 6.0.0-2.
https://github.com/multiarch/qemu-user-static/commit/097659180b0447bc333746adfd5b2959be4ab70d
