### ISSUE TITLE
Tags for 6.1.0 not found in Docker hub

### ISSUE THREAD

**Issue by verokarhu** [multiarch/qemu-user-static#157]
Tags for 6.1.0 not found in Docker hub despite the documentation claiming that they should be available.

Latest version tag on Docker hub is https://hub.docker.com/layers/multiarch/qemu-user-static/5.2.0-2/images/sha256-14ef836763dd8a1d69927699811f89338b129faa3bd9eb52cd696bc3d84aa81a?context=explore

/kind bug

**Comment by srbala** [comment]
@verokarhu I believe the newer version available as `latest` tag, released a month ago. https://hub.docker.com/layers/multiarch/qemu-user-static/latest/images/sha256-b44f8140fcefa9a7db48139c5dbbd8e887119f663360b1f413d842693c7ba746?context=explore
You are right there is no `6.1.x` tag available for direct reference.

Team, any reason newer number tags are not published?

**Comment by lafin** [comment]
@verokarhu thanks for the information about this issue. fixed in the last release.
https://hub.docker.com/r/multiarch/qemu-user-static/tags?page=1&name=6.1.0
