### ISSUE TITLE
QEMU 6.2.0 support

### ISSUE THREAD

**Issue by iii-i** [multiarch/qemu-user-static#164]
**Is this a bug report, feature (enhancement) request or question? (leave only one on its own line)**

/kind enhancement

**Description:**

QEMU 6.2.0 has been released the last December (https://www.qemu.org/2021/12/14/qemu-6-2-0/) - do you have plans to make a new multiarch/qemu-user-static release?

**Comment by h-vetinari** [comment]
There's a PR for this in https://github.com/multiarch/qemu-user-static/pull/167
