### ISSUE TITLE
debug application running in the container from image arm32v7/ubuntu

### ISSUE THREAD

**Issue by mbajlo** [multiarch/qemu-user-static#165]
How to debug arm32 application running in the docker?

Description:
I am having a problem with the application debug. The problem is when I try to debug the application with the gdb on the docker I get the error:
```
warning: Could not trace the inferior process.
warning: ptrace: Function not implemented
During startup program exited with code 127.
```
and from what I've understood, this is because the QEMU is not supporting `ptrace` so I cannot use `gdb` . I was reading about `gdbstub `built in the QEMU, but there I understood this is for kernel/OS debug and not for the application debug in the running docker container.

Is there a way to debug an application running in the QEMU emulated arm32 container?

Environment:
host:
Linux DESKTOP-2ADE3Q8 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

container:
Linux arm32 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 armv7l armv7l armv7l GNU/Linux

Docker version 20.10.12, build e91ed57

**Comment by martin-g** [comment]
You need to run `docker run --cap-add=SYS_PTRACE  ...` for ptrace

**Comment by mbajlo** [comment]
The solution is to install `qemu-user` and `qemu-user-static` in the docker. on the Docker start the application with GDB stub on which you can connect from the host via `gdb-multiarch`.

which means:

1. in the docker container start the application built with 
    `gcc -g...` like this qemu-arm localhost:1234 ./app.out
2. on the host environment(my is ubuntu 20.04 LTS) run
    `gdb-multiarch -q --nh -ex 'set architecture arm' -ex 'file app.out' -ex 'target remote docker_container_ip:1234'`
and that is it.

**Comment by alter-xp** [comment]
> The solution is to install `qemu-user` and `qemu-user-static` in the docker. on the Docker start the application with GDB stub on which you can connect from the host via `gdb-multiarch`.

Based on my attempts, mounting the qemu-user-static (like qemu-arm.)from the host machine into the container(-v /usr/bin/qemu-arm:/usr/bin/qemu-arm) is faster than directly installing qemu in Docker. It simplifies the process from qemu -> qemu -> elf to qemu -> elf.
