### ISSUE TITLE
Intermittent exec format error when building linux/arm64 (alpine 3.15+) on amd64 host

### ISSUE THREAD

**Issue by kevin-lindsay-1** [multiarch/qemu-user-static#175]
**Is this a bug report, feature (enhancement) request or question? (leave only one on its own line)**

/kind bug

**Description:**

I have a docker container that builds, and commands will randomly fail with `exec format error`. I can provide this dockerfile upon request.

**Steps to reproduce the issue:**

**Describe the results you received:**

**Describe the results you expected:**

**Environment:**

* QEMU version: (if you can know it): 7.0.0-7
* Container application: Docker/Podman/Singularity (Leave only one): docker

**Output of `docker version`, `podman version` or `singularity version`**
`docker:20.10.17` running with `buildx:0.8.2`

**Additional information optionally:**
I have tried many different version tweaks, and this error just keeps occurring unpredictably. I'm not 100% sure it's caused by QEMU, but I run this same build on `linux/amd64` and it has failed 0% of the time (running in parallel).

**Comment by martin-g** [comment]
The report as is is not actionable.
Please provide a reproducer!
