### ISSUE TITLE
Register ppc64le too

### ISSUE THREAD

**Issue by luxas** [multiarch/qemu-user-static#2]
Hi and thanks for the awesome work!
I'm trying to build an image `FROM ppc64le/debian:jessie` that only installs iptables.
`COPY qemu-ppc64le-static /usr/bin/` is there but `docker run --rm --privileged multiarch/qemu-user-static:register --reset` doesn't register `ppc64le`, only ppc which obviously doesn't work.
Is there any issues with registering `ppc64le` or could we do it?

**Comment by moul** [comment]
Hi @luxas, 

You can `docker pull multiarch/qemu-user-static:register` to refresh the image with **ppc64le** support

Successfully tested with

```Dockerfile
FROM ppc64le/debian:jessie
COPY qemu-ppc64le-static
```

And

```console
moul@fwrz:~# docker run -it --rm multiarch/ubuntu-core:ppc64el-vivid
root@6b1f08a0a622:/# uname -a
Linux 6b1f08a0a622 4.2.0-23-generic #28-Ubuntu SMP Sun Dec 27 17:47:31 UTC 2015 ppc64le ppc64le ppc64le GNU/Linux
```

**Comment by luxas** [comment]
Thank you so much!
