### ISSUE TITLE
Wtf Am I doing?

### ISSUE THREAD

**Issue by Iacolopes** [multiarch/qemu-user-static#205]
https://github.com/mona-actions/gh-repo-stats/blob/zerotyr-security-policy/gh-repo-stats#L1-L79

**Comment by junaruga** [comment]
@Iacolopes What does this issue ticket mean?
I also see you approved the following old PR that was merged in January 2023. Why?
https://github.com/multiarch/qemu-user-static/pull/183

@moul @lafin I think you need to be aware of this.
