### ISSUE TITLE
Update to v2.9

### ISSUE THREAD

**Issue by luxas** [multiarch/qemu-user-static#21]
Hi, I'm a big fan of your QEMU builds, thank you!

Now that v2.9.0 was released this week, would you mind upgrading to the latest version?
Cheers!

**Comment by lafin** [comment]
Sure, we are waiting update a deb packages http://ftp.debian.org/debian/pool/main/q/qemu/.

**Comment by hurricanehrndz** [comment]
@lafin, how instead of debs, the rpms from openSUSE Tumbleweed are used. The rpm can be extracted using rpm2cpio. The builds are static anyhow so any package from any distro should do.

**Comment by moul** [comment]
Do you have a link to the package so we can give a try?

**Comment by hurricanehrndz** [comment]
Here is my container that was inspired by yours:
https://github.com/MediaBrowser/Emby.Build/tree/master/docker-containers/qemu-builder/register

You might also want to checkout this code that I use in my make files
``` 
 repo := http://download.opensuse.org/tumbleweed/repo/oss/suse/x86_64
      $(eval rpm_name := $(shell curl -s $(repo)/ --list-only | grep qemu-linux | sed -n s%".*>\(qemu-linux-.*rpm\)</a>.*"%"\1"%p | tail -1))
    curl -L $(repo)/$(rpm_name) -o /var/tmp/$(IMG_NAME)_$(ARCH)/qemu-linux-user.rpm
    @ if [[ $(ARCH) ==  "armv7l" ]]; then \
        rpm2cpio /var/tmp/$(IMG_NAME)_$(ARCH)/qemu-linux-user.rpm | cpio -D /var/tmp/$(IMG_NAME)_$(ARCH)/ -idmv "*qemu-arm" "*qemu-arm-*"; \
      fi
    @ if [[ $(ARCH) ==  "aarch64" ]]; then \
        rpm2cpio /var/tmp/$(IMG_NAME)_$(ARCH)/qemu-linux-user.rpm | cpio -D /var/tmp/$(IMG_NAME)_$(ARCH)/ -idmv "*qemu-aarch*"; \
      fi
    sed -i '/ENV/,/RUN/ {s/^$$/COPY usr \/usr/}' /var/tmp/$(IMG_NAME)_$(ARCH)/Dockerfile
    @ if [[ ! -e /proc/sys/fs/binfmt_misc/arm || ! -e /proc/sys/fs/binfmt_misc/aarch64 ]]; then \
        docker run --rm --privileged emby/qemu-builder:register; \
      fi
```

Hopefully the above give you enough code to proceed

**Comment by hurricanehrndz** [comment]
Sorry just noticed it was still on 2.8, it is rolling release so it might be a bit faster at updating.

**Comment by luxas** [comment]
Thanks @lafin :+1:

**Comment by frivoire** [comment]
Hello,

I have seen this update to 2.9.0 and it seems it can cause some issue :
==> those new builds aren't **static** anymore

Here is what I've tested:
```
flo@flopc:~$ wget -q https://github.com/multiarch/qemu-user-static/releases/download/v2.8.4/qemu-aarch64-static -O - |file -
/dev/stdin: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, BuildID[sha1]=91fb924228a0814f7ae7d13947cb1f13c02fa36f, stripped
```
```
flo@flopc:~$ wget -q https://github.com/multiarch/qemu-user-static/releases/download/v2.9.0/qemu-aarch64 -O - |file -
/dev/stdin: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=48894fc6b031f7dfecf8ac90b6f420dd8d94b34f, stripped
```

And in https://github.com/multiarch/qemu-user-static/releases/tag/v2.9.0, several files are named "-static" but are not :
- qemu-aarch64-static.tar.gz
- x86_64_qemu-aarch64-static.tar.gz
Those 2 contain the same binary than qemu-aarch64

The change (static -> dynamic) seems to come from this commit:
https://github.com/multiarch/qemu-user-static/commit/6226ce549420e779e71c79c28623eab73ec68644

I believe that this repo should still provide **static** builds (as it did until 2.8.4).
For now, can we stick to debian (even if still on 2.8) ? Or try to use builds from another distrib (as suggested by hurricanehrndz) ?

Thanks !

**Comment by superseed** [comment]
It also seems that on Arch, the only static version of `qemu-user` is in the [AUR](https://aur.archlinux.org/packages/qemu-user-static/).
