### ISSUE TITLE
qemu-user-static is not static anymore

### ISSUE THREAD

**Issue by moul** [multiarch/qemu-user-static#24]
See https://github.com/multiarch/centos/issues/2#issuecomment-305443286

It's a recent issue:
* v2.9.0 is KO
* v2.8.4 is OK

**Comment by frivoire** [comment]
Another issue related :  https://github.com/multiarch/qemu-user-static/issues/21

**Comment by lafin** [comment]
I released [2.9.1](https://github.com/multiarch/qemu-user-static/releases/tag/v2.9.1) from the fedora package for https://github.com/multiarch/qemu-user-static/issues/21#issuecomment-306430284. Can you check centos?

**Comment by moul** [comment]
It's fixed for Centos, thanks
