### ISSUE TITLE
> 2.9.1 speed regression with qemu-arm-static?

### ISSUE THREAD

**Issue by uSpike** [multiarch/qemu-user-static#35]
I'm trying to use `qemu-arm-static` in a debian stretch based docker image, built from a debootstrap, using raspbian mirrors.

I've noticed that `qemu-arm-static` versions newer than 2.9.1 are *really* slow.  It takes 10x or 20x as long for `apt-get` operations to run, for example.  My host machine is x86_64, Ubuntu 16.04 (4.13.0-37-generic).

Just wondering if anyone else has seen this regression?  I can provide more information if it's useful.

**Comment by lafin** [comment]
try the latest version the qemu-user-static 2.12.0 for me time to build was minimized.

**Comment by RaymondMouthaan** [comment]
tried v2.12.0 which solved performance issue for me 💯 

@lafin thanks for your quick response! 🥇
