### ISSUE TITLE
Arm64

### ISSUE THREAD

**Issue by anandkolli** [multiarch/qemu-user-static#36]
Hi,

I am trying run qemu-user-static:register on arm based machine (aarch64) and I am getting the below error please take a look
root@arm-ucpe-test:~# uname -a
Linux arm-ucpe-test 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:33:57 UTC 2017 aarch64 aarch64 aarch64 GNU/Linux

root@arm-ucpe-test:~# docker run --rm --privileged multiarch/qemu-user-static:register
standard_init_linux.go:178: exec user process caused "no such file or directory"

So is this tested on aarch64?
Please let me know if you need more information.

Thanks,
Anand

**Comment by vielmetti** [comment]
I'm able to replicate the problem:

```
% uname -a
Linux ed-2a-bcc-llvm 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:33:57 UTC 2017 aarch64 aarch64 aarch64 GNU/Linux
```

with this error message instead of yours

```
standard_init_linux.go:178: exec user process caused "exec format error"
```

**Comment by vielmetti** [comment]
And the reason for this is that the multiarch/qemu-user-static:register image is amd64 only:

```
root@ed-2a-bcc-llvm:~# docker run --rm mplatform/mquery multiarch/qemu-user-static:register
Image: multiarch/qemu-user-static:register
 * Manifest List: No
 * Supports: amd64/linux
```

**Comment by junaruga** [comment]
Currently "multiarch/qemu-user-static" does not support aarch64 as a host architecture.
We needs to add new implementation for that. I am considering to add the feature. But not soon.
You can check this similar project: https://github.com/dbhi/qus

**Comment by junaruga** [comment]
We created the unified ticket for this unsupported non-x86_64 host architecture here https://github.com/multiarch/qemu-user-static/issues/77 . You can subscribe it.
I like to close this ticket for the duplicated ticket.

But you can reopen this ticket, if you need it.
Thanks.
