### ISSUE TITLE
Various errors when compiling on armv7h using qemu-arm-static

### ISSUE THREAD

**Issue by Strit** [multiarch/qemu-user-static#43]
Hi there. For some time now I have had a couple of errors pop up when running with qemu-arm-static inside an armv7h chroot for crosscompiling armv7h software.

Most notable and annoying ones are:

**QT**
I get missing modules (these vary depending on project) when compiling QT applications:
```
Project ERROR: Unknown module(s) in QT: core gui widgets
Project ERROR: Unknown module(s) in QT: core
```
The exact same procedure, with qemu-aarch64-static in an aarch64 chroot works fine.
It also builds fine on an armv7h device without qemu at all.

**GTK**
I get unrecognised image formats when compiling some GTK apps. Like this one:
```
[3/71] Generating manager_resources_h with a custom command.
FAILED: resources/manager_resources.h 
glib-compile-resources ../resources/pamac.manager.gresource.xml --sourcedir ../resources --internal --generate --target resources/manager_resources.h
failed to load "../resources/package-available.png": Couldn?t recognize the image file format for file ?../resources/package-available.png?
../resources/pamac.manager.gresource.xml: Child process exited with code 1.
[4/71] Generating manager_resources_c with a custom command.
FAILED: resources/manager_resources.c 
glib-compile-resources ../resources/pamac.manager.gresource.xml --sourcedir ../resources --internal --generate --target resources/manager_resources.c --dependency-file resources/manager_resources.c.d
failed to load "../resources/package-available.png": Couldn?t recognize the image file format for file ?../resources/package-available.png?
../resources/pamac.manager.gresource.xml: Child process exited with code 1.
[11/71] Compiling Vala source ../src/common_daemon.vala ../src/package.vala ../src/pamac_config.vala ../src/alpm_config.vala ../src/aur.vala ../src/system_daemon.vala.
ninja: build stopped: subcommand failed.
```
Again, it builds fine with aarch64 instead and on the armv7h device directly.

I am at a loss here, I even tried different versions of the qemu-arm-static file, but they all had the same issues.
I'm using qemu 2.12, qemu-user-static 2.12 and systemd 239 (for systemd-nspawn).

**Comment by junaruga** [comment]
Hi @Strit Could you try the latest multi/qemu-user-static? The latest version is 4.0.0.

We also released new image `multiarch/qemu-user-static` that can build and run standard architecture image instead of multiarch compatible images.

```
$ uname -m
x86_64

$ docker run --rm -t arm64v8/ubuntu uname -m
standard_init_linux.go:211: exec user process caused "exec format error"

$ docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

$ docker run --rm -t arm64v8/ubuntu uname -m
aarch64
```

Thanks.

**Comment by Strit** [comment]
Sorry. We have since dropped armv7h support, so it is no longer an issue for us.

**Comment by junaruga** [comment]
Sure. Okay. Thanks for sharing it.
