### ISSUE TITLE
Big endian arch to add multiarch Dockerhub

### ISSUE THREAD

**Issue by junaruga** [multiarch/qemu-user-static#47]
I want to add big endian arch environment (`ppc64` (not `ppc64le`), `s390x`) for this project.
But I have no idea how to add it.
Can we add the big endian arch docker container to the DockerHub [1]?

Thank you.

[1] https://hub.docker.com/r/multiarch/ubuntu-debootstrap/tags/

**Comment by junaruga** [comment]
Sorry I could run big endian arch `s390x` using https://hub.docker.com/r/multiarch/debian-debootstrap/tags/ .
I close this ticket.

Thank you, multiarch project!

```
docker run --rm --privileged multiarch/qemu-user-static:register --reset
docker run --rm -t multiarch/debian-debootstrap:s390x-jessie uname -a
Linux e774bfd6a08e 4.13.0-1008-gcp #11-Ubuntu SMP Thu Jan 25 11:08:44 UTC 2018 s390x GNU/Linux
```

**Comment by jeking3** [comment]
Did you try to do anything with it?  Once you try to run a command it fails; and the jessie s390x files no longer exist.  In fact I cannot find a big endian image that actually works.  Every time it tries to hit the network it fails.
