### ISSUE TITLE
"write pipe: bad file descriptor" on aarch64

### ISSUE THREAD

**Issue by vielmetti** [multiarch/qemu-user-static#8]
Environment: multicore ARMv8 machine running Ubuntu 16.04.

Trying to follow directions, and I get this:

```
emv@armv8hello:~$ docker run --rm --privileged multiarch/qemu-user-static:register
Unable to find image 'multiarch/qemu-user-static:register' locally
register: Pulling from multiarch/qemu-user-static
8ddc19f16526: Already exists 
5ac0057b3331: Pull complete 
Digest: sha256:ee56b87e8debafb7c6ed2a2d2b7c2b5f9d471e4bee0cb84956f97d0316f4bc59
Status: Downloaded newer image for multiarch/qemu-user-static:register
write pipe: bad file descriptor
```

I have a feeling I'm missing something, perhaps a longer README about getting started.

thanks!

Ed

**Comment by junaruga** [comment]
Currently "multiarch/qemu-user-static" does not support aarch64 as a host architecture.
We needs to add new implementation for that. I am considering to add the feature. But not soon.
You can check this similar project: https://github.com/dbhi/qus

**Comment by umarcor** [comment]
Hi @vielmetti! As @junaruga suggested, you can use images provided by project [dbhi/qus](https://github.com/dbhi/qus):

``` bash
# Clean any previously registered interpreter
docker run --rm --privileged aptman/qus -- -r

# Register interpreter for amd64 on an aarch64 host
docker run --rm --privileged aptman/qus -s -- -p amd64

# Build/run your docker images
docker run --rm -it amd64/ubuntu bash -c 'uname -m'
```

**Comment by junaruga** [comment]
@umarcor thanks for sharing the examples! Yes, let's close this ticket because of the duplicated ticket.
